"use client";
import React, { useEffect, useState } from "react";
import Link from "next/link";
import { useDarkMode } from "../hooks/use-dark-mode";
import { dateFromParts, differenceInCalendarDays, isValidDate } from "../lib/date-utils";

const monthNames = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"];
export default function DateCalculator() {
  const { darkMode } = useDarkMode(); const monthsMap = Object.fromEntries(monthNames.map((m, i) => [m, i])); const days = Array.from({ length: 31 }, (_, i) => String(i + 1)); const years = Array.from({ length: 101 }, (_, i) => String(2035 - i));
  const [startMonth, setStartMonth] = useState("Jan"), [startDay, setStartDay] = useState("1"), [startYear, setStartYear] = useState("2026");
  const [endMonth, setEndMonth] = useState("Jan"), [endDay, setEndDay] = useState("1"), [endYear, setEndYear] = useState("2026");
  const [daysDiff, setDaysDiff] = useState<number | null>(null); const [error, setError] = useState<string | null>(null);
  useEffect(() => { const today = new Date(), m = monthNames[today.getMonth()], d = String(today.getDate()), y = String(today.getFullYear()); setStartMonth(m); setStartDay(d); setStartYear(y); setEndMonth(m); setEndDay(d); setEndYear(y); }, []);
  const calculateDifference = (event: React.FormEvent) => {
    event.preventDefault();
    if (!isValidDate(Number(startYear), monthsMap[startMonth], Number(startDay)) || !isValidDate(Number(endYear), monthsMap[endMonth], Number(endDay))) { setError("Please select valid calendar dates."); setDaysDiff(null); return; }
    const start = dateFromParts(Number(startYear), monthsMap[startMonth], Number(startDay));
    const end = dateFromParts(Number(endYear), monthsMap[endMonth], Number(endDay));
    setError(null);
    setDaysDiff(Math.abs(differenceInCalendarDays(end, start)));
  };
  const selectClass = `border rounded-md p-2 text-[10px] flex-1 outline-none ${darkMode ? "bg-slate-700 border-slate-600" : "bg-white border-gray-200"}`;
  const fields = (month: string, setMonth: (v: string) => void, day: string, setDay: (v: string) => void, year: string, setYear: (v: string) => void) => <div className="flex gap-1"><select value={month} onChange={(e) => setMonth(e.target.value)} className={selectClass}>{monthNames.map((v) => <option key={v}>{v}</option>)}</select><select value={day} onChange={(e) => setDay(e.target.value)} className={selectClass}>{days.map((v) => <option key={v}>{v}</option>)}</select><select value={year} onChange={(e) => setYear(e.target.value)} className={selectClass}>{years.map((v) => <option key={v}>{v}</option>)}</select></div>;
  return <div className={`w-full min-h-screen flex flex-col transition-colors duration-300 ${darkMode ? "bg-slate-900 text-slate-100" : "bg-[#f8fafc] text-[#333]"}`}><header className={`w-full border-b py-3 px-4 flex justify-center sticky top-0 z-50 ${darkMode ? "bg-slate-800 border-slate-700 shadow-md" : "bg-white border-gray-200 shadow-sm"}`}><div className="w-full max-w-[1050px] flex items-center justify-between"><Link href="/" className="flex items-center gap-2"><img src="/icon.png" alt="logo" className="h-8 w-8 rounded-full object-cover" /><span className={`text-base font-black tracking-tight ${darkMode ? "text-white" : "text-[#2b5880]"}`}>chronos-calc</span></Link><Link href="/" className={`text-[10px] font-black uppercase tracking-wider px-2.5 py-1 rounded-md border ${darkMode ? "text-gray-400 border-slate-700 hover:text-white" : "text-gray-500 border-gray-100"}`}>â† Home</Link></div></header>
    <div className="w-full max-w-[1050px] mx-auto px-4 pt-6 pb-20 flex-1 flex flex-col md:flex-row gap-6 justify-center items-start"><div className={`w-full md:w-[65%] border rounded-2xl shadow-xl overflow-hidden ${darkMode ? "bg-slate-800 border-slate-700" : "bg-white border-gray-200"}`}><div className="bg-[#3b6e9c] text-white text-[10px] font-black py-2 px-4 text-center uppercase tracking-[0.2em]">Engine: Date Calculator Engine v1.0</div><div className="p-5 sm:p-8"><form onSubmit={calculateDifference} className="flex flex-col gap-4"><div className="grid grid-cols-1 sm:grid-cols-2 gap-4"><div className="flex flex-col gap-1.5"><label className="text-[10px] font-black text-gray-400">START DATE</label>{fields(startMonth, setStartMonth, startDay, setStartDay, startYear, setStartYear)}</div><div className="flex flex-col gap-1.5"><label className="text-[10px] font-black text-gray-400">END DATE</label>{fields(endMonth, setEndMonth, endDay, setEndDay, endYear, setEndYear)}</div></div><button type="submit" className="bg-[#5c940d] text-white font-black py-3 px-6 rounded-xl mt-2 text-xs uppercase tracking-widest">Check Variance</button>{error && <p role="alert" className="text-sm font-bold text-red-600">{error}</p>}{daysDiff !== null && <div className={`mt-4 p-5 rounded-xl border text-center font-black text-xl text-[#3b6e9c] ${darkMode ? "bg-slate-900/50 border-slate-700" : "bg-blue-50 border-blue-100"}`}>{daysDiff} Days Variance</div>}</form></div></div>
      <div className={`w-full md:w-[35%] border rounded-2xl p-5 shadow-lg ${darkMode ? "bg-slate-800 border-slate-700" : "bg-white border-gray-200"}`}><h2 className="text-[11px] font-black uppercase tracking-widest text-[#3b6e9c] dark:text-sky-400 mb-3 border-b pb-1">âš™ï¸ How To Use</h2><div className="text-[11px] text-gray-400 leading-relaxed flex flex-col gap-2.5"><p><strong>1. Kya Daalna Hai:</strong> Pehli box me Start Date aur doosri box me End Date select karein.</p><p><strong>2. Kaise Kaam Karega:</strong> Compute Variance par click karte hi engine dono dino ke beech ke exact total days (din) scan kar ke nikal dega.</p><p><strong>3. Use Case:</strong> Project deadlines calculate karne, travel planning travel gaps check karne, aur long timeline target scheduling ke liye helpful hai.</p></div></div></div></div>;
}
