"use client";
import React, { useState } from "react";
import Link from "next/link";
import { useDarkMode } from "../hooks/use-dark-mode";
export default function TimeCalculator() {
  const { darkMode } = useDarkMode(); const hours = Array.from({ length: 24 }, (_, i) => String(i).padStart(2, "0")); const minutes = Array.from({ length: 60 }, (_, i) => String(i).padStart(2, "0"));
  const [startHour, setStartHour] = useState("09"), [startMinute, setStartMinute] = useState("00"), [endHour, setEndHour] = useState("17"), [endMinute, setEndMinute] = useState("00"); const [duration, setDuration] = useState<string | null>(null);
  const calculateTime = (event: React.FormEvent) => { event.preventDefault(); let total = Number(endHour) * 60 + Number(endMinute) - Number(startHour) * 60 - Number(startMinute); if (total < 0) total += 1440; setDuration(`${Math.floor(total / 60)} Hours and ${total % 60} Minutes`); };
  const selectClass = `border rounded p-2 text-xs flex-1 outline-none ${darkMode ? "bg-slate-700 border-slate-600" : "bg-white border-gray-200"}`;
  const fields = (hour: string, setHour: (v: string) => void, minute: string, setMinute: (v: string) => void) => <div className="flex gap-1"><select value={hour} onChange={(e) => setHour(e.target.value)} className={selectClass}>{hours.map((v) => <option key={v}>{v}</option>)}</select><select value={minute} onChange={(e) => setMinute(e.target.value)} className={selectClass}>{minutes.map((v) => <option key={v}>{v}</option>)}</select></div>;
  return <div className={`w-full min-h-screen flex flex-col transition-colors duration-300 ${darkMode ? "bg-slate-900 text-slate-100" : "bg-[#f8fafc] text-[#333]"}`}><header className={`w-full border-b py-3 px-4 flex justify-center sticky top-0 z-50 ${darkMode ? "bg-slate-800 border-slate-700 shadow-md" : "bg-white border-gray-200 shadow-sm"}`}><div className="w-full max-w-[1050px] flex items-center justify-between"><Link href="/" className="flex items-center gap-2"><img src="/icon.png" alt="logo" className="h-8 w-8 rounded-full object-cover" /><span className={`text-base font-black tracking-tight ${darkMode ? "text-white" : "text-[#2b5880]"}`}>chronos-calc</span></Link><Link href="/" className={`text-[10px] font-black uppercase tracking-wider px-2.5 py-1 rounded-md border ${darkMode ? "text-gray-400 border-slate-700 hover:text-white" : "text-gray-500 border-gray-100"}`}>← Hub</Link></div></header>
  <div className="w-full max-w-[1050px] mx-auto px-4 pt-6 pb-20 flex-1 flex flex-col md:flex-row gap-6 justify-center items-start"><div className={`w-full md:w-[65%] border rounded-2xl shadow-xl overflow-hidden ${darkMode ? "bg-slate-800 border-slate-700" : "bg-white border-gray-200"}`}><div className="bg-[#3b6e9c] text-white text-[10px] font-black py-2 px-4 text-center uppercase tracking-[0.2em]">Engine: Time Calculator Engine v1.0</div><div className="p-5 sm:p-8"><form onSubmit={calculateTime} className="flex flex-col gap-4"><div className="grid grid-cols-2 gap-4"><div className="flex flex-col gap-2"><label className="text-[10px] font-black text-gray-400 uppercase">Start Time</label>{fields(startHour, setStartHour, startMinute, setStartMinute)}</div><div className="flex flex-col gap-2"><label className="text-[10px] font-black text-gray-400 uppercase">End Time</label>{fields(endHour, setEndHour, endMinute, setEndMinute)}</div></div><button type="submit" className="bg-[#5c940d] text-white font-black py-3 px-6 rounded-xl text-xs uppercase tracking-widest">Analyze Gap</button>{duration && <div className={`mt-4 p-5 rounded-xl border text-center text-base font-black uppercase text-[#5c940d] ${darkMode ? "bg-slate-900/50 border-slate-700" : "bg-green-50 border-green-100"}`}>{duration}</div>}</form></div></div>
  <div className={`w-full md:w-[35%] border rounded-2xl p-5 shadow-lg ${darkMode ? "bg-slate-800 border-slate-700" : "bg-white border-gray-200"}`}><h2 className="text-[11px] font-black uppercase tracking-widest text-[#3b6e9c] dark:text-sky-400 mb-3 border-b pb-1">⚙️ How To Use</h2><div className="text-[11px] text-gray-400 leading-relaxed flex flex-col gap-2.5"><p><strong>1. Kya Daalna Hai:</strong> Entry logs me Start Time (kaam shuru hone ka samay) aur End Time (khatam hone ka samay) clock system se feed karein.</p><p><strong>2. Kaise Kaam Karega:</strong> Compute Duration dabayein. Engine overnight matrix tracking calculations auto-resolve karke total Hours aur Minutes display karega.</p><p><strong>3. Use Case:</strong> Employee shift mapping, study tracking sessions logs, aur daily workout time lapse analyze karne ke liye optimized hai.</p></div></div></div></div>;
}
